-- @author: wangbing
-- 2018-05-22

local pointConfig={
	EVENT_MJ_CHUANQI = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "传奇来了", ["winID"] = "79VWYFQJZ", ["btnName"] = "传奇来了", ["btnID"] = "XETQOPSZY", ["time"] = "2018-05-16 18:02:14", ["btnDes"] = "大厅传奇来了按钮"},
	EVENT_MJ_YULE = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "娱乐大厅", ["winID"] = "3NYBZ2LH7", ["btnName"] = "娱乐大厅", ["btnID"] = "H40FC5JVA", ["time"] = "2018-05-16 18:01:13", ["btnDes"] = "大厅娱乐大厅按钮"},
	EVENT_MJ_SPORT = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "比赛场", ["winID"] = "YK12OMTU4", ["btnName"] = "比赛场", ["btnID"] = "3W875SECE", ["time"] = "2018-05-16 18:00:12", ["btnDes"] = "大厅比赛场按钮"},
	EVENT_MJ_PDKBTN = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "跑得快", ["winID"] = "KOJ6XMZZZ", ["btnName"] = "跑得快", ["btnID"] = "RIBWHZOG9", ["time"] = "2018-05-16 17:59:46", ["btnDes"] = "大厅跑得快按钮"},
	EVENT_MJ_MJBTN = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "湖南麻将", ["winID"] = "VRZGUMZ83", ["btnName"] = "湖南麻将", ["btnID"] = "E4NQ89RNM", ["time"] = "2018-05-16 17:59:28", ["btnDes"] = "大厅湖南麻将按钮"},
	EVENT_MJ_CLUB = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "亲友圈", ["winID"] = "ZSV0TDMFP", ["btnName"] = "亲友圈", ["btnID"] = "BTUX2361Q", ["time"] = "2018-05-16 17:59:09", ["btnDes"] = "大厅亲友圈按钮"},
	EVENT_MJ_ADDDEMEND = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "钻石", ["winID"] = "040I8808H", ["btnName"] = "钻石充值", ["btnID"] = "UHIAS1UQG", ["time"] = "2018-05-16 17:57:53", ["btnDes"] = "大厅上方钻石充值按钮"},
	EVENT_MJ_ADDCOIN = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "金币", ["winID"] = "NUALBEBR8", ["btnName"] = "金币充值", ["btnID"] = "ML151T68X", ["time"] = "2018-05-16 17:57:39", ["btnDes"] = "大厅上方金币充值按钮"},
	EVENT_MJ_ADDFANGKA = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "房卡", ["winID"] = "VXI7WT0DO", ["btnName"] = "房卡充值", ["btnID"] = "5ZEZAHWK6", ["time"] = "2018-05-16 17:56:59", ["btnDes"] = "大厅上方房卡充值按钮"},
	EVENT_MJ_USERCENTER = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "个人信息", ["winID"] = "ETZUDRBWU", ["btnName"] = "个人信息", ["btnID"] = "K0FMN8477", ["time"] = "2018-05-16 17:54:01", ["btnDes"] = "大厅个人信息按钮"},
	EVENT_MJ_ACTIVITY = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "活动", ["winID"] = "REAIHZH65", ["btnName"] = "活动", ["btnID"] = "KGS58GNVK", ["time"] = "2018-05-16 17:52:44", ["btnDes"] = "大厅活动按钮"},
	EVENT_MJ_HISTORY = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "战绩", ["winID"] = "56QVRBJ3E", ["btnName"] = "战绩", ["btnID"] = "AYKURPJZQ", ["time"] = "2018-05-16 17:51:31", ["btnDes"] = "大厅战绩按钮"},
	EVENT_MJ_SHARE = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "分享", ["winID"] = "7IBDYZ8SY", ["btnName"] = "分享", ["btnID"] = "61T6HSKE6", ["time"] = "2018-05-16 17:50:21", ["btnDes"] = "大厅分享按钮"},
	EVENT_MJ_KEFU = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "客服", ["winID"] = "UNDW1OW7W", ["btnName"] = "客服", ["btnID"] = "OJMPU0IPO", ["time"] = "2018-05-16 17:42:13", ["btnDes"] = "大厅客服按钮"},
	EVENT_MJ_MORE = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "更多", ["winID"] = "YO9HNINSE", ["btnName"] = "更多", ["btnID"] = "HCP012HD7", ["time"] = "2018-05-16 17:40:07", ["btnDes"] = "大厅下方更多按钮"},
	EVENT_MJ_CERTIFLCATION = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "更多", ["winID"] = "YO9HNINSE", ["btnName"] = "实名", ["btnID"] = "U8NOK37XM", ["time"] = "2018-05-16 17:35:10", ["btnDes"] = "大厅-更多-实名按钮"},
	EVENT_MJ_VERIFY = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "更多", ["winID"] = "YO9HNINSE", ["btnName"] = "安全验证", ["btnID"] = "HE818QSWD", ["time"] = "2018-05-16 17:24:35", ["btnDes"] = "大厅-更多-安全验证按钮"},
	EVENT_MJ_WANFA = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "更多", ["winID"] = "YO9HNINSE", ["btnName"] = "玩法", ["btnID"] = "WWD5N16T2", ["time"] = "2018-05-16 17:22:49", ["btnDes"] = "大厅-更多-玩法按钮"},
	EVENT_MJ_MSG = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "更多", ["winID"] = "YO9HNINSE", ["btnName"] = "消息1", ["btnID"] = "IDFEL5DDR", ["time"] = "2018-05-16 17:22:26", ["btnDes"] = "大厅-更多-消息按钮"},
	EVENT_MJ_SETTING = {["gameName"] = "闲来麻将", ["serverID"] = 10001, ["eventName"] = "大厅界面", ["eventID"] = "E70OCHGO5", ["winName"] = "更多", ["winID"] = "YO9HNINSE", ["btnName"] = "设置", ["btnID"] = "90A09UTUM", ["time"] = "2018-05-16 17:16:17", ["btnDes"] = "大厅-更多-设置按钮"},
}

return pointConfig